### ISSUE TITLE
chore(Deps): discord.js v12

### ISSUE THREAD

**Issue by conrmahr** [conrmahr/nhl-discord-bot#25]
**Please describe the changes this PR makes and why it should be merged:**
> Discord has announced breaking API changes that will not be implemented into discord.js version 11.  We expect this to happen around October 2020. Along with this we decided to no longer maintain bug fixes or new features for version 11 of discord.js. Please [update your bot to version 12](https://discordjs.guide/additional-info/changes-in-v12.html) at your earliest convenience.

- Bump discord.js from v11 to 12 

**Status**
- [ ] Code changes have been tested against the NHL API, or there are no code changes

**Semantic versioning classification:**  
- [x] This PR changes the app's interface (methods or parameters added)
  - [x] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.
