### ISSUE TITLE
chore(Deps): discord.js v13

### ISSUE THREAD

**Issue by conrmahr** [conrmahr/nhl-discord-bot#63]
**Please describe the changes this PR makes and why it should be merged:**
> discord.js v13 makes the switch to Discord API v9! In addition to this, the new major version also includes a bunch of cool new features. [Updating from v12 to v13](https://discordjs.guide/additional-info/changes-in-v13.html)

- Bump discord.js from v12 to v13 

**Status**
- [ ] Code changes have been tested against the NHL API, or there are no code changes

**Semantic versioning classification:**  
- [x] This PR changes the app's interface (methods or parameters added)
  - [x] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.
